name: XCS234_A3_CUDA
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.10
  - notebook=6.5.4
  - tk=8.6.12
  - ffmpeg=4.2.2
  - moviepy=1.0.3
  - scipy=1.10.1
  - tensorboard=2.12.1
  - pyyaml=6.0.1
  - pip=23.3
  - pip:
    - matplotlib==3.7.3
    - imageio==2.32.0 
    - numpy==1.24.4
    - pygame==2.5.2
    - dm-control==1.0.15
    - gym==0.26.2
    - mujoco==3.0.0
    - "--find-links https://download.pytorch.org/whl/torch_stable.html"
    - torch==2.1.0+cu118
